# from https://github.com/pypa/sampleproject

name: test-pr

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: ['3.10']
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install test dependencies
        run: python -m pip install --upgrade nox

      - name: Test
        run: |
          cd compiler/tools/example_package_subfolder
          python -m nox -s tests-${{ matrix.python }}

      - name: Lint
        run: |
          cd compiler/tools/example_package_subfolder
          python -m nox -s lint
